### ISSUE TITLE
Grid instead of list

### ISSUE THREAD

**Issue by Klammerson** [mike1pol/octoprint_macro#1]
Since I'm having some issues with the wide screen plugin combined with your plugin (screen starts shifting back and forth) but was able to fix it, expanding my other sidebar, I have some suggestions:

Instead of the buttons aligned in a single column list, I'd love to see them arranged in a grid or multi column (maybe as a configurable option!?)

Compatibility for customization with Themify would be awesome!

Nevertheless I love your work and appreciate what you have achieved here! Thanks!

**Comment by mike1pol** [comment]
Ok, I'll take a look and try to fix it.

**Comment by Klammerson** [comment]
Awesome work realizing this. Thx
