### ISSUE TITLE
Version 0.3.1 does not update version number, sticks in infinite update loop

### ISSUE THREAD

**Issue by AlAmantea** [mike1pol/octoprint_macro#26]
**Describe the bug**

Version 0.3.1 does not update version number, sticks in infinite update loop

**To Reproduce**
1. Update to 0.3.1
2. upon restart, version still reports as 0.3.0 and asks to update again

**Expected behavior**

Version should automatically update to 0,3,1

**Screenshots**

**Versions (please complete the following information):**
 - OctoPrint: [e.g. 2.4.1]
 - Version [e.g. 0.3.0]

**Additional context**

**Comment by ejhoness** [comment]
thank you very much for your words, they are of great value to me, with each click, thank you very much. and everyone for everything :D
mee too ,

**Comment by mike1pol** [comment]
fixed in version 0.3.2
