### ISSUE TITLE
Multi Line Gcode Can Be Extremely inconsistent!

### ISSUE THREAD

**Issue by Dracrius** [mike1pol/octoprint_macro#7]
If a line of gcode ends with a `,` or `;` it will inconsistently execute. I had this set
```
G91;
G1 F3000 Z20 ;
G28 X Y;
G90;
G1 X0 Y235 F1000;
M84
```
And it was all over the place on which lines it would us, sometimes only running the first 3, other times running only the third etc.

It appears to work as expected if you enter 1 line of gcode per line with no punctuation or comments.

**Comment by mike1pol** [comment]
1 line per 1 command.
for comments use ``;;`` on new line or after gcode line

**Comment by mike1pol** [comment]
do it work?

**Comment by dannieboiz** [comment]
I'm also having this issue, trying to move X, y to 117 and Z to 0

I've tried G0 X117, y117, z0 and G0 X117; y117; z0 also putting those one on per line none works can you please give an example of what it would look like?

**Comment by meltonpieman** [comment]
dannieboiz
I have used multiple commands on one line with no seperators, such as
  G26 B60 H210 L0.3 R1
and had no problems
David

**Comment by dannieboiz** [comment]
Thanks, issue was me... In terminal it isn't case sensitive but in this plugin it is, G0 X117 G0 Y117 G0 Z0 works.

G0 X117 isn't the same as G0 x117 it seems LOL

**Comment by mike1pol** [comment]
need to convert all commands to uppercase before executing a command
